### ISSUE TITLE
Plot output 

### ISSUE THREAD

**Issue by JuliusWelzel** [neurogeriatricskiel/pymocap#1]
Hey, 

could we add inputs to make plotting the data optional, with the default being False? 
e.g.:  def pijnappels(heel_pos, toe_pos, fs,**plot_data = False**, **kwargs):
and use this for the now commented out plotting section?

**Comment by rmndrs89** [comment]
Dear @JuliusWelzel,

thanks for your interest in the repo. My idea is to have this option available via the optional keyword argument "visualize":

```python
# Get kwargs
visualize = kwargs.get("visualize", False)
```
and then:
```python
if visualize == True:
    fig, axs = plt.subplots(nrows=X, ncols=Y)
    ...
```

This will be available in future commits.
